//
//  GreetingModels.swift
//  CleanSwift
//
//  Created by Вячеслав Квашнин on 05.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

typealias GreetingViewModel = Greeting.ShowGreeting.ViewModel
typealias GreetingRequest = Greeting.ShowGreeting.Request
typealias GreetingResponse = Greeting.ShowGreeting.Response

enum Greeting {
 
    // MARK: Набор юзкейсов для сцены Greeting
    enum ShowGreeting {
        // посредник между вью и интерактором
        struct Request {
            
        }
        // посредник между интерактором и презентером
        struct Response {
            let name: String
            let surname: String
        }
        // посредник между презентером и вью
        struct ViewModel {
            let greeting: String
        }
    }
}
